use TURMAB;

select DAY(data_venda) from VENDAS;
select month(data_venda) from VENDAS;
select YEAR(data_venda) from VENDAS;

SELECT date_format(data_venda, '%m/%d/%Y'), data_venda
from VENDAS;

-- 1 - O GERENTE PRECISA DE UM RELATÓRIO DO NOME DOS CLIENTES 
-- EXIBIDO EM ORDEM ALFABÉTICA

SELECT nome_cliente FROM VENDAS
ORDER BY nome_cliente; -- CRESCENTE SEM ASC

SELECT * FROM VENDAS
ORDER BY nome_cliente ASC; -- CRESCENTE COM ASC

-- O GERENTE PRECISA DE UM RELATÓRIO DE VENDAS ORDENADAS PELA MAIS CARA
SELECT * FROM VENDAS
ORDER BY valor DESC;

-- O GERENTE PRECISA DE UM RELATÓRIO DAS 10 VENDAS MAIS RECENTES
-- PAGAS COM PIX
SELECT 
	date_format(data_venda, '%d/%m/%Y'), 
	nome_cliente,
	cpf_cliente,
	valor,
	forma_pagamento
FROM 
	VENDAS
WHERE 
	forma_pagamento = 'Pix'
ORDER BY 
	data_venda DESC
LIMIT 10;

/*  **TABELA VENDAS
    1 - QUAIS FORAM AS 10 MAIORES VENDAS FEITAS NO CARTÃO DE CRÉDITO
    2 - QUAIS VENDAS FORA REALIZADAS EM MARÇO DE 2025? ORDENADAS DA MAIS RECENTE PRA MAIS ANTIGA
    3 - QUAIS CLIENTES COMPRARAM PRODUTOS COM VALOR ATÉ MIL REAIS, ORDENADOS PELO NOME

   ** TABELA PRODUTOS
    4 - QUAIS PRODUTOS VENDIDOS FORAM FABRICADOS NO JAPÃO? ORDENE DO MAIOR VALOR PARA O MENOR
    5 - QUAIS PRODUTOS DISPONÍVEIS PARA VENDA TÊM VALOR ACIMA DE 5 MIL, ORDENADOS POR CATEGORIA ALFABETICAMENTE?
    6 - QUAIS OS 5 PRODUTOS MAIS CAROS QUE FORAM VENDIDOS, DA MARCA LG?

   ******BÔNUS
    7 - CRIE UM RELATÓRIO COM A QUANTIDADE DE VENDAS REALIZADA EM CADA MÊS, DO MAIS RECENTE PRO MAIS NOVO
*/
