-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 20:41:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TURMAB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TURMAB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TURMAB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `TURMAB` ;

-- -----------------------------------------------------
-- Table `TURMAB`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TURMAB`.`PRODUTOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NULL DEFAULT NULL,
  `modelo` VARCHAR(50) NULL DEFAULT NULL,
  `categoria` VARCHAR(30) NULL DEFAULT NULL,
  `tipo_conexao` VARCHAR(30) NULL DEFAULT NULL,
  `cor` VARCHAR(30) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `ano_aquisicao` INT NULL DEFAULT NULL,
  `pais_fabricacao` VARCHAR(50) NULL DEFAULT NULL,
  `status_venda` VARCHAR(20) NULL DEFAULT NULL,
  `codigo` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TURMAB`.`VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TURMAB`.`VENDAS` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NOT NULL,
  `email_cliente` VARCHAR(100) NULL DEFAULT NULL,
  `data_venda` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `forma_pagamento` VARCHAR(100) NOT NULL,
  `observacoes` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `VENDAS_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `TURMAB`.`PRODUTOS` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
