/*  **TABELA VENDAS
    1 - QUAIS FORAM AS 10 MAIORES VENDAS FEITAS NO CARTÃO DE CRÉDITO
    2 - QUAIS VENDAS FORA REALIZADAS EM MARÇO DE 2025? ORDENADAS DA MAIS RECENTE PRA MAIS ANTIGA
    3 - QUAIS CLIENTES COMPRARAM PRODUTOS COM VALOR ATÉ MIL REAIS, ORDENADOS PELO NOME

   ** TABELA PRODUTOS
    4 - QUAIS PRODUTOS VENDIDOS FORAM FABRICADOS NO JAPÃO? ORDENE DO MAIOR VALOR PARA O MENOR
    5 - QUAIS PRODUTOS DISPONÍVEIS PARA VENDA TÊM VALOR ACIMA DE 5 MIL, ORDENADOS POR CATEGORIA ALFABETICAMENTE?
    6 - QUAIS OS 5 PRODUTOS MAIS CAROS QUE FORAM VENDIDOS, DA MARCA LG?

   ******BÔNUS
    7 - CRIE UM RELATÓRIO COM A QUANTIDADE DE VENDAS REALIZADA EM CADA MÊS, DO MAIS RECENTE PRO MAIS NOVO
*/

-- 1 - QUAIS FORAM AS 10 MAIORES VENDAS FEITAS NO CARTÃO DE CRÉDITO
SELECT *
FROM VENDAS
ORDER BY valor DESC
LIMIT 10;

-- 2- QUAIS VENDAS FORA REALIZADAS EM MARÇO DE 2025? ORDENADAS DA MAIS RECENTE PRA MAIS ANTIGA
SELECT *
FROM VENDAS
WHERE data_venda BETWEEN '2025-03-01' AND '2025-03-31'
ORDER BY data_venda DESC;

-- 3 - QUAIS CLIENTES COMPRARAM PRODUTOS COM VALOR ATÉ MIL REAIS, ORDENADOS PELO NOME
SELECT *
FROM VENDAS
WHERE valor <= 1000.00
ORDER BY nome_cliente;

-- visualizar tabela PRODUTOS
SELECT * FROM PRODUTOS;
-- 4 - QUAIS PRODUTOS VENDIDOS FORAM FABRICADOS NO JAPÃO? ORDENE DO MAIOR VALOR PARA O MENOR
SELECT *
FROM PRODUTOS
WHERE pais_fabricacao LIKE 'Japão'
AND status_venda LIKE 'Vendido'
ORDER BY valor DESC;

--  5 - QUAIS PRODUTOS DISPONÍVEIS PARA VENDA TÊM VALOR ACIMA DE 5 MIL, ORDENADOS POR CATEGORIA ALFABETICAMENTE?
SELECT *
FROM PRODUTOS
WHERE status_venda LIKE 'Disponível'
AND valor > 5000.00
ORDER BY categoria;

-- 6 - QUAIS OS 5 PRODUTOS MAIS CAROS QUE FORAM VENDIDOS, DA MARCA LG?
SELECT *
FROM PRODUTOS
WHERE marca LIKE 'LG'
ORDER BY valor DESC
LIMIT 5;


-- 7 - CRIE UM RELATÓRIO COM A QUANTIDADE DE VENDAS REALIZADA EM CADA MÊS, DO MAIS RECENTE PRO MAIS ANTIGO
SELECT GROUP()