
SELECT * FROM PRODUTOS;
SELECT * FROM CLIENTES;
SELECT * FROM VENDAS;

/*
	1 - NOME, O CPF, O TELEFONE E O EMAIL DE CLIENTES QUE FIZERAM COMPRAS ACIMA DE 5 MIL REAIS;
    2 - NOME, CPF E TELEFONE DE CLIENTES QUE FIZERAM COMPRAS EM 2025
    3 - NOME E DO TELEFONE DE CLIENTES QUE FIZERAM COMPRAS E TENHAM DDD 61
    4 - VALOR DE VENDA DE TODOS OS PRODUTOS DA LG VENDIDOS NA LOJA
*/

